# Generated by Django 2.1.1 on 2018-09-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='category',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
