# Generated by Django 2.1.1 on 2018-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science', '0002_auto_20180913_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='friendly_title',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
