# Generated by Django 2.1.1 on 2018-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science', '0003_algorithm_friendly_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='friendly_category',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
