# Generated by Django 2.1.1 on 2018-09-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science', '0004_algorithm_friendly_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='friendly_category',
            field=models.SlugField(default=None),
        ),
    ]
