# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-16 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computer_science', '0006_auto_20180913_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='algorithm_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
